# MongoDB
MONGO_HOST: str = ...
MONGO_PORT: int = ...
MONGO_USERNAME: str = ...
MONGO_PASSWORD: str = ...
MONGO_AUTH_DB_NAME: str = ...
MONGO_DB_NAME: str = ...

# MinIO
MINIO_HOST: str = ...
MINIO_PORT: int = ...
MINIO_ACCESS_KEY: str = ...
MINIO_SECRET_KEY: str = ...
