# MongoDB
MONGO_HOST: str = '91.218.8.186'
MONGO_PORT: int = 27017
MONGO_USERNAME: str = 'alex_savelev'
MONGO_PASSWORD: str = 'insane_password'
MONGO_AUTH_DB_NAME: str = 'admin'
MONGO_DB_NAME: str = 'offer'

# MinIO
MINIO_HOST: str = ...
MINIO_PORT: int = ...
MINIO_ACCESS_KEY: str = ...
MINIO_SECRET_KEY: str = ...
